
DIR=`basename ${PWD}`

DATA_IMAGE=$PROJECT_HOME/data/$DIR/data_batch_1.bin

SNAPSHOTS=$PROJECT_HOME/snapshots/$DIR/

EXECUTABLE=$PROJECT_HOME/bin/$DIR/demo.bin

echo $DATA_IMAGE $SNAPSHOTS

gdb $EXECUTABLE

