all:
	g++ -O3 -g0 -Wno-write-strings main.cpp -o picker -I../../../include/file_input/ -I../../../include/visualization/ -I../../../include/machine_learning_tools/ -I../../../include/diagnostics/ -lboost_thread -lboost_system -lGL -lGLU -lglut;
	g++ -O3 -g0 -Wno-write-strings best_fit_plane_test.cpp -o fit -I../../../include/file_input/ -I../../../include/visualization/ -I../../../include/machine_learning_tools/ -I../../../include/diagnostics/ -lboost_thread -lboost_system -lGL -lGLU -lglut;
